apiVersion: v1
kind: ConfigMap
metadata:
  name: sermant-injector
  namespace: {{ .Values.namespace.name }}
  labels:
    app: sermant-injector
data:
  # Configuration center type
  SERMANT_AGENT_CONFIG_TYPE: {{ .Values.config.type }}
  # Configuration center address
  SERMANT_AGENT_CONFIG_ADDRESS: {{ .Values.config.endpoints }}
  # Registration center type
  SERMANT_AGENT_SERVICE_TYPE: {{ .Values.registry.type }}
  # Registration center address
  SERMANT_AGENT_SERVICE_ADDRESS: {{ .Values.registry.endpoints }}
  # Agent image address
  SERMANT_AGENT_IMAGE_ADDR: {{ .Values.agent.image.addr }}
  # Agent image pulling policy
  SERMANT_AGENT_IMAGE_PULLPOLICY: {{ .Values.agent.image.pullPolicy }}
  # Injector injection action
  SERMANT_AGENT_INJECT_ACTION: {{ .Values.injector.action }}
  {{- if not (and .Values.configMap.enabled .Values.configMap.namespaces) }}
  # External agent image address
  SERMANT_AGENT_EXTERNALAGENT_IMAGEADDR: {{ .Values.externalAgent.imageAddr }}
  # External agent file name in image
  SERMANT_AGENT_EXTERNALAGENT_FILENAME: {{ .Values.externalAgent.fileName }}
  SERMANT_AGENT_CONFIGMAP: ""
  {{- end }}
