router.plugin:
  # whether compatible with the sermant-springboot-registry plugin
  enabled-registry-plugin-adaptation: false
  # whether to use xds route
  enabled-xds-route: false
  # whether to use secure protocol to invoke spring cloud downstream service with xds route, example: http or https
  enabled-springcloud-xds-route-secure: false
  # Whether to use request information for routing
  use-request-router: false
  # Use request information as tags when routing
  request-tags: []
  # the tag of the request header to be resolved
  parse-header-tag: ''
  # Whether to initialize DUBBO zone routing (compatibility switch)，Once enabled, a routing with the same label that
  # matches the zone will be initialized in the Dubbo configuration cache
  enabled-dubbo-zone-router: false
  # Whether to initialize the spring cloud area routing (compatibility switch), Once enabled, a routing with the same
  # label that matches the zone will be initialized in the spring cloud configuration cache
  enabled-spring-zone-router: false
  # compatibility router config 1.0, default is false not support
  enabled-previous-rule: false
  # Whether to Enable Metrics Collection
  enable-metric: false
transmit.plugin:
  # Whether to transmit the label on the direct new thread
  enabled-thread: true
  # Whether to transmit the label in the pool of non-scheduled thread pool
  enabled-thread-pool: true
  # Whether to transmit the label in the schedule/scheduleAtFixedRate/scheduleWithFixedDelay method of the scheduled
  # thread pool
  enabled-scheduler: false
