name: "Agent-core Common Test"
description: "Auto test for agent-core common"
runs:
  using: "composite"
  steps:
    - name: entry
      uses: ./.github/actions/common/entry
      with:
        log-dir: ./logs/agentcore-test/common
    - name: modify config
      shell: bash
      run: |
        sed -i 's/service\.meta\.application=default/service.meta.application=testApplication/' sermant-agent-${{ env.sermantVersion }}/agent/config/config.properties
    - name: start applications
      shell: bash
      env:
        dynamic.config.serverAddress: 127.0.0.1:2181
        dynamic.config.dynamicConfigType: ZOOKEEPER
        service.meta.project: TestAgentCore
      run: |
        nohup java -javaagent:sermant-agent-${{ env.sermantVersion }}/agent/sermant-agent.jar -jar \
        sermant-agent-${{ env.sermantVersion }}/agent/agentcore-test-application-1.0.0-jar-with-dependencies.jar > ${{ env.logDir
        }}/agentcore-test.log 2>&1 &
    - name: waiting for agentcore services start
      shell: bash
      run: |
        bash ./sermant-integration-tests/scripts/checkService.sh http://127.0.0.1:8915/ping 120
    - name: agentcore test config load start
      shell: bash
      run: mvn test -Dagentcore.test.type=CONFIG_LOAD --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml
    - name: agentcore test enhancement
      shell: bash
      run: mvn test -Dagentcore.test.type=COMMON_ENHANCE --file sermant-integration-tests/agentcore-test/agentcore-integration-test/pom.xml
    - name: exit
      if: always()
      uses: ./.github/actions/common/exit
      with:
        processor-keyword: agentcore
    - name: if failure then upload error log
      uses: actions/upload-artifact@v4
      if: ${{ failure() || cancelled() }}
      with:
        name: agentcore-test-common-logs
        path: |
          ./*.log
          ./logs/**
        if-no-files-found: warn
        retention-days: 2
